In [31]:
import os
import re
import json
import math

from IPython.display import JSON

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from dotenv import load_dotenv

from google import genai
from google.genai import types
from ydata_profiling import ProfileReport

In [32]:
df = pd.read_csv(r"C:\Users\shubh\Desktop\Auto EDA\My work\Zomato Restaurant Dataset.csv")

def get_dataframe_metadata(df):

    metadata = {
        "row_count": len(df),
        "column_count": len(df.columns),
        "columns": {}
    }

    for column in df.columns:

        metadata["columns"][column] = {
            "dtype": str(df[column].dtype),
            "missing_count": int(df[column].isna().sum()),
            "unique_count": int(df[column].nunique()),
            "sample_values": (
                df[column]
                .dropna()
                .head(5)
                .tolist()
            )
        }

    return metadata

metadata = get_dataframe_metadata(df)

In [33]:
def get_analysis_questions(report_path, metadata_path):
    
    with open(report_path, "r", encoding="utf-8") as f:
        mod_report = json.load(f)

    prompt = f"""
    You are a senior data analyst. The dataset is already cleaned.
    Your goal is to find potential trends in this data. Do NOT summarize
    the dataset or describe the report. Only propose questions worth
    asking and the aggregations that would answer them.

    Use the metadata to understand what each column means, and the
    profiling report to see which columns are usable (cardinality,
    distribution, date ranges, correlations).

    First, classify columns internally as:
    - Dimensions (categories to group by, e.g. country, product, segment)
    - Measures (numeric values to aggregate, e.g. revenue, count, price)
    - Time columns (dates or periods)

    Then generate analysis questions in these categories:

    1. Aggregation by a dimension
       (e.g. total or average of a measure by country)
    2. Drill-down within a dimension
       (e.g. within a country, break down by region, product, or segment)
    3. Trends over time
       (e.g. monthly or yearly change in a measure, overall or per group)
    4. Comparisons across groups
       (e.g. top vs bottom performers, share of total, ranking changes)
    5. Relationships between columns
       (e.g. does measure A change with measure B or a category)
    6. Concentration and outliers
       (e.g. do a few groups drive most of the total, which groups
       behave unlike the rest)

    For each question, give:
    - The question, in plain language
    - Columns involved
    - The aggregation (sum, mean, median, count, ratio, growth rate)
      and the grouping level
    - What kind of trend or pattern it could reveal

    Rules:
    - Only use columns that exist in the metadata or report.
    - Skip columns that are unsuitable (e.g. IDs, near-constant columns,
      very high-cardinality categories for grouping).
    - Prefer questions where the report hints at something interesting
      (skew, strong correlation, imbalance, wide date range).
    - Do not write Python code or run any analysis.
    - Do not recommend data cleaning.
    - Do not claim a trend exists. Phrase everything as a question
      to investigate.
    - Give 10 to 15 questions, ordered from most to least promising.

    Metadata:
    {metadata}

    Profiling report:
    {json.dumps(mod_report)}
    """

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

In [34]:
# Example

analysis_questions = get_analysis_questions("mod_report.json", metadata)

print(analysis_questions)

Here's an analysis plan with questions and aggregations to find potential trends in the restaurant data.

---

**Column Classification:**

*   **Dimensions:** `Country Code`, `City`, `Locality`, `Cuisines`, `Currency`, `Has Table booking`, `Has Online delivery`, `Price range`, `Rating color`, `Rating text`.
*   **Measures:** `Average Cost for two`, `Aggregate rating`, `Votes`.
*   **Time columns:** None identified in the profiling report (`"time_index_analysis": "None"`), so no questions for this category.

**Analysis Questions:**

1.  **Question:** What are the top 5 countries with the highest average restaurant ratings?
    *   **Columns involved:** `Country Code`, `Aggregate rating`
    *   **Aggregation:** Mean of `Aggregate rating`, grouped by `Country Code`.
    *   **Trend/Pattern:** Identifies regions with overall higher customer satisfaction or service quality.

2.  **Question:** Which cities have the highest concentration of restaurants, and how does this relate to their average aggregate rating?
    *   **Columns involved:** `City`, `Restaurant ID`, `Aggregate rating`
    *   **Aggregation:** Count of distinct `Restaurant ID` (number of restaurants) and mean of `Aggregate rating`, grouped by `City`.
    *   **Trend/Pattern:** Reveals popular restaurant hubs and whether density correlates with perceived quality.

3.  **Question:** What are the most prevalent cuisine types offered by restaurants, and how do their average ratings compare?
    *   **Columns involved:** `Cuisines` (requires splitting into individual cuisines), `Aggregate rating`
    *   **Aggregation:** Count of individual cuisines, and mean of `Aggregate rating` for each cuisine type.
    *   **Trend/Pattern:** Highlights popular culinary trends and which cuisines generally receive better customer feedback.

4.  **Question:** How does the average cost for two people vary across different price ranges and countries?
    *   **Columns involved:** `Country Code`, `Price range`, `Average Cost for two`
    *   **Aggregation:** Mean of `Average Cost for two`, grouped by `Country Code` and `Price range`.
    *   **Trend/Pattern:** Shows how pricing strategies differ by region and across different price segments. (The `Average Cost for two` is highly skewed, suggesting variation).

5.  **Question:** Is there a relationship between offering table booking or online delivery and higher aggregate ratings or more votes?
    *   **Columns involved:** `Has Table booking`, `Has Online delivery`, `Aggregate rating`, `Votes`
    *   **Aggregation:** Mean of `Aggregate rating` and mean of `Votes`, grouped by `Has Table booking` and `Has Online delivery` (separately or combined).
    *   **Trend/Pattern:** Determines if specific amenities/services contribute to better customer perception or engagement. (Correlations noted in report).

6.  **Question:** What proportion of restaurants in each city have an `Aggregate rating` of 0 (unrated), and what are the characteristics of these restaurants (e.g., average cost, price range)?
    *   **Columns involved:** `City`, `Aggregate rating`, `Restaurant ID`, `Average Cost for two`, `Price range`
    *   **Aggregation:** Percentage of `Restaurant ID` where `Aggregate rating` is 0, and average cost/price range for these unrated restaurants, grouped by `City`.
    *   **Trend/Pattern:** Identifies areas with a high number of new, niche, or underperforming establishments. (22.5% of `Aggregate rating` are zeros).

7.  **Question:** Within cities with a high number of restaurants, are there specific `Localities` that stand out for exceptionally high or low average ratings?
    *   **Columns involved:** `City`, `Locality`, `Aggregate rating`
    *   **Aggregation:** Mean of `Aggregate rating`, grouped by `City` and then `Locality`, focusing on cities with high restaurant counts.
    *   **Trend/Pattern:** Pinpoints specific high-quality or low-quality dining areas within major urban centers.

8.  **Question:** How does the distribution of `Price range` categories differ between countries?
    *   **Columns involved:** `Country Code`, `Price range`, `Restaurant ID`
    *   **Aggregation:** Count of `Restaurant ID` for each `Price range`, expressed as a percentage of total restaurants in that `Country Code`.
    *   **Trend/Pattern:** Reveals national preferences or market structures regarding restaurant affordability.

9.  **Question:** Do restaurants with 'Excellent' or 'Very Good' `Rating text` tend to receive significantly more `Votes` than those with lower ratings like 'Average' or 'Poor'?
    *   **Columns involved:** `Rating text`, `Votes`
    *   **Aggregation:** Mean of `Votes`, grouped by `Rating text`.
    *   **Trend/Pattern:** Explores the relationship between perceived quality (rating text) and customer engagement/popularity (votes). (Strong correlation between `Rating text` and `Aggregate rating` which correlates with `Votes`).

10. **Question:** Are there outlier restaurants with extremely high `Average Cost for two` or `Votes` that significantly skew the averages for their respective categories (e.g., city, cuisine, price range)?
    *   **Columns involved:** `Average Cost for two`, `Votes`, `City`, `Cuisines`, `Price range`
    *   **Aggregation:** Identify maximum values and their corresponding restaurant/group, and compare to median/mean values within each `City`, `Cuisines`, or `Price range`.
    *   **Trend/Pattern:** Highlights exceptional cases of luxury dining, highly popular spots, or potential data anomalies. (`Average Cost for two` and `Votes` are highly skewed).

11. **Question:** How do the different `Rating color` categories (e.g., Dark Green, Yellow, Red) correspond to the `Price range` of restaurants?
    *   **Columns involved:** `Rating color`, `Price range`, `Restaurant ID`
    *   **Aggregation:** Count of `Restaurant ID`, grouped by `Rating color` and `Price range`.
    *   **Trend/Pattern:** Investigates if certain price points are more likely to achieve specific rating levels.

12. **Question:** What is the ratio of restaurants offering online delivery in countries where Indian Rupee is the currency versus other currencies?
    *   **Columns involved:** `Currency`, `Has Online delivery`, `Restaurant ID`
    *   **Aggregation:** Proportion of "Yes" in `Has Online delivery`, grouped by `Currency`.
    *   **Trend/Pattern:** Highlights potential regional differences or market maturity in adopting online delivery services, especially for the most common currency. (Currency is highly imbalanced, Indian Rupees is dominant).

13. **Question:** Are there any specific cities where `Longitude` or `Latitude` values are frequently zero, potentially indicating missing or default geographic data?
    *   **Columns involved:** `City`, `Longitude`, `Latitude`, `Restaurant ID`
    *   **Aggregation:** Count of `Restaurant ID` where `Longitude` is 0 or `Latitude` is 0, grouped by `City`.
    *   **Trend/Pattern:** Identifies data quality issues or specific urban areas where location data might be incomplete, which could impact spatial analysis. (5.2% zeros for both Longitude and Latitude).

In [35]:


def generate_analysis_functions(analysis_questions, df_metadata):

    prompt = f"""
    You are a Python data-analysis function generator.

    INPUT 1: ANALYSIS QUESTIONS
    {analysis_questions}

    INPUT 2: DATAFRAME METADATA
    {json.dumps(df_metadata, default=str)}

    YOUR TASK:
    Generate one small Python function per analysis question.
    Each function computes the aggregation that answers the
    question and returns the result as a DataFrame.

    RULES:
    1. Generate one function per question. Skip questions that
       cannot be answered with the available columns.
    2. Use the exact DataFrame column names provided.
    3. Each function must accept df as its only argument.
    4. Each function must return a pandas DataFrame (the result
       table), never a plain number, string, or plot.
    5. Do not modify the original DataFrame. Work on a copy.
    6. Do not invent columns or assume unsupported facts.
    7. Only pandas (pd) is available. Do not include imports,
       plotting, file I/O, or print statements.
    8. Do not clean data. Assume the DataFrame is already clean.
    9. For time trends, convert date columns inside the function
       only if needed, and group by period (month, quarter, year).
    10. For drill-downs, group by the parent dimension first,
        then the child dimension.
    11. Keep results readable: sort sensibly, reset the index,
        and limit very long outputs with .head(20) where it makes
        sense (e.g. top groups).
    12. Where useful, add derived columns such as share_of_total
        or growth_rate to the result.
    13. Do not use Markdown code fences.

    RETURN FORMAT:
    Return valid JSON with this structure:
    {{
        "functions": [
            {{
                "name": "function_name",
                "question": "the analysis question in plain language",
                "columns": ["column_name"],
                "group_by": ["column_name"],
                "aggregation": "sum / mean / count / growth_rate etc.",
                "code": "complete Python function as a string"
            }}
        ]
    }}

    Return an empty functions list if no question can be
    answered safely with the available columns.
    """

    response = client.models.generate_content(
        model="gemini-3.7-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            temperature=0.1,
            response_mime_type="application/json"
        )
    )

    return response.text

In [36]:
import pandas as pd
from IPython.display import display

response_data = json.loads(generate_analysis_functions(analysis_questions, metadata))

results = {}

for func_data in response_data["functions"]:
    function_name = func_data["name"]

    try:
        namespace = {"pd": pd}
        exec(func_data["code"], namespace)

        analysis_function = namespace[function_name]
        result_df = analysis_function(df.copy())
        results[function_name] = result_df

        print(f"\n{'=' * 80}")
        print(f"{function_name}")
        print(f"Question: {func_data['question']}")
        print(f"{'=' * 80}")
        display(result_df)

    except Exception as e:
        print(f"\n[FAILED] {function_name} — {type(e).__name__}: {e}")

================================================================================
top_countries_by_rating
Question: What are the top 5 countries with the highest average restaurant ratings?
================================================================================

   Country Code  mean_aggregate_rating
0           162               4.468182
1           208               4.300000
2            94               4.295238
3           148               4.262500
4           214               4.233333

================================================================================
restaurant_density_and_rating_by_city
Question: Which cities have the highest concentration of restaurants, and how does this relate to their average aggregate rating?
================================================================================

            City  restaurant_count  mean_aggregate_rating
0      New Delhi              5473               2.438845
1        Gurgaon              1118               2.651431
2          Noida              1080               2.036204
3      Faridabad               251               1.866932
4      Ghaziabad                25               2.852000
5   Bhubaneshwar                21               3.980952
6        Lucknow                21               4.195238
7       Guwahati                21               4.190476
8      Ahmedabad                21               4.161905
9       Amritsar                21               3.685714
10     Abu Dhabi                20               4.300000
11        Albany                20               3.555000
12          Agra                20               3.965000
13      Savannah                20               4.155000
14         Surat                20               3.935000
15       Augusta                20               4.130000
16    Aurangabad                20               3.375000
17      Auckland                20               4.275000
18        Athens                20               4.200000
19        Ankara                20               4.305000

================================================================================
prevalent_cuisines_and_ratings
Question: What are the most prevalent cuisine types offered by restaurants, and how do their average ratings compare?
================================================================================

        Cuisines  cuisine_count  mean_aggregate_rating
0   North Indian           3960               2.510455
1        Chinese           2735               2.621024
2      Fast Food           1986               2.563092
3        Mughlai            995               2.609950
4        Italian            764               3.562042
5         Bakery            745               2.440940
6    Continental            736               3.518750
7           Cafe            703               3.321195
8       Desserts            653               2.978867
9   South Indian            636               2.469811
10   Street Food            562               2.356050
11      American            390               3.661538
12         Pizza            381               2.921785
13        Mithai            380               2.073684
14        Burger            251               3.520717
15          Thai            234               3.659829
16         Asian            233               3.815021
17     Beverages            229               2.740175
18     Ice Cream            226               2.583186
19       Mexican            181               3.723204

================================================================================
avg_cost_by_country_and_price_range
Question: How does the average cost for two people vary across different price ranges and countries?
================================================================================

    Country Code  Price range  mean_average_cost_for_two
0              1            1                 284.384168
1              1            2                 620.125962
2              1            3                1257.875788
3              1            4                2582.860825
4             14            1                   7.000000
5             14            2                  20.000000
6             14            3                  30.000000
7             14            4                 120.000000
8             30            1                  30.000000
9             30            2                  49.285714
10            30            3                  74.687500
11            30            4                 185.142857
12            37            2                  25.000000
13            37            4                  70.000000
14            94            2               70000.000000
15            94            3              291750.000000
16           148            1                  23.333333
17           148            2                  38.750000
18           148            3                  53.529412
19           148            4                 103.437500
20           162            2                 600.000000
21           162            3                 954.166667
22           162            4                2588.888889
23           166            2                  50.000000
24           166            3                  86.000000
25           166            4                 285.357143
26           184            2                  20.000000
27           184            3                  42.000000
28           184            4                 206.071429
29           189            2                 141.250000
30           189            3                 242.882353
31           189            4                 525.384615
32           191            2                1266.666667
33           191            3                2490.909091
34           191            4                4166.666667
35           208            2                  43.181818
36           208            3                  80.000000
37           208            4                 194.000000
38           214            2                  63.333333
39           214            3                 137.758621
40           214            4                 246.363636
41           215            1                  13.750000
42           215            2                  26.428571
43           215            3                  44.375000
44           215            4                 100.625000
45           216            1                   9.338235
46           216            2                  25.000000
47           216            3                  39.681818
48           216            4                  69.130435

================================================================================
service_options_impact_on_rating_and_votes
Question: Is there a relationship between offering table booking or online delivery and higher aggregate ratings or more votes?
================================================================================

,Has Table booking,Has Online delivery,mean_aggregate_rating,mean_votes,restaurant_count
0,No,No,2.365062,122.025404,6377
1,No,Yes,3.173958,154.559524,2016
2,Yes,No,3.349378,280.186722,723
3,Yes,Yes,3.595862,474.303448,435

================================================================================
unrated_restaurants_characteristics_by_city
Question: What proportion of restaurants in each city have an Aggregate rating of 0 (unrated), and what are the characteristics of these restaurants?
================================================================================

,City,total_restaurants,unrated_count,pct_unrated,unrated_avg_cost,unrated_avg_price_range
0,New Delhi,5473,1425,26.036908,323.249123,1.196491
1,Gurgaon,1118,228,20.393560,384.868421,1.298246
2,Noida,1080,384,35.555556,374.609375,1.304688
3,Faridabad,251,100,39.840637,378.500000,1.300000
4,Ghaziabad,25,2,8.000000,300.000000,1.000000
5,Bhubaneshwar,21,0,0.000000,NaN,NaN
6,Lucknow,21,0,0.000000,NaN,NaN
7,Guwahati,21,0,0.000000,NaN,NaN
8,Ahmedabad,21,0,0.000000,NaN,NaN
9,Amritsar,21,0,0.000000,NaN,NaN
10,Abu Dhabi,20,0,0.000000,NaN,NaN
11,Albany,20,0,0.000000,NaN,NaN
12,Agra,20,0,0.000000,NaN,NaN
13,Savannah,20,0,0.000000,NaN,NaN
14,Surat,20,0,0.000000,NaN,NaN
15,Augusta,20,0,0.000000,NaN,NaN
16,Aurangabad,20,0,0.000000,NaN,NaN
17,Auckland,20,0,0.000000,NaN,NaN
18,Athens,20,0,0.000000,NaN,NaN
19,Ankara,20,0,0.000000,NaN,NaN

================================================================================
localities_rating_in_top_cities
Question: Within cities with a high number of restaurants, are there specific Localities that stand out for exceptionally high or low average ratings?
================================================================================

,City,Locality,mean_aggregate_rating,restaurant_count
0,Faridabad,Sector 15,3.429032,31
1,Faridabad,"Vibe by The LaLit Traveller, Mathura Road",3.300000,1
2,Faridabad,Sector 86,3.172727,11
3,Faridabad,Sector 19,3.150000,2
4,Faridabad,"The Atrium, Suraj Kund",3.050000,2
...,...,...,...,...
491,Noida,"Park Ascent, Sector 62, Noida",0.000000,1
492,Noida,Sector 1,0.000000,2
493,Noida,Sector 127,0.000000,1
494,Noida,Sector 57,0.000000,1
495,Noida,Sector 60,0.000000,3

================================================================================
price_range_distribution_by_country
Question: How does the distribution of Price range categories differ between countries?
================================================================================

    Country Code  Price range  restaurant_count  percentage_share
0              1            1              4295         49.641701
1              1            2              2858         33.032825
2              1            3              1111         12.840962
3              1            4               388          4.484512
4             14            1                 4         16.666667
5             14            2                14         58.333333
6             14            3                 5         20.833333
7             14            4                 1          4.166667
8             30            1                 2          3.333333
9             30            2                 7         11.666667
10            30            3                16         26.666667
11            30            4                35         58.333333
12            37            2                 3         75.000000
13            37            4                 1         25.000000
14            94            2                 1          4.761905
15            94            3                20         95.238095
16           148            1                 3          7.500000
17           148            2                 4         10.000000
18           148            3                17         42.500000
19           148            4                16         40.000000
20           162            2                 1          4.545455
21           162            3                12         54.545455
22           162            4                 9         40.909091
23           166            2                 1          5.000000
24           166            3                 5         25.000000
25           166            4                14         70.000000
26           184            2                 1          5.000000
27           184            3                 5         25.000000
28           184            4                14         70.000000
29           189            2                 4          6.666667
30           189            3                17         28.333333
31           189            4                39         65.000000
32           191            2                 6         30.000000
33           191            3                11         55.000000
34           191            4                 3         15.000000
35           208            2                11         32.352941
36           208            3                18         52.941176
37           208            4                 5         14.705882
38           214            2                 9         15.000000
39           214            3                29         48.333333
40           214            4                22         36.666667
41           215            1                 4          5.000000
42           215            2                28         35.000000
43           215            3                32         40.000000
44           215            4                16         20.000000
45           216            1               136         31.336406
46           216            2               165         38.018433
47           216            3               110         25.345622
48           216            4                23          5.299539

================================================================================
votes_by_rating_text
Question: Do restaurants with 'Excellent' or 'Very Good' Rating text tend to receive significantly more Votes than those with lower ratings like 'Average' or 'Poor'?
================================================================================

  Rating text  mean_votes  median_votes  total_votes  restaurant_count
0   Excellent  851.770764         489.0       256383               301
1   Very Good  520.458758         271.0       561575              1079
2        Good  229.351429         121.0       481638              2100
3        Poor   90.715054          61.0        16873               186
4     Average   48.249130          20.0       180307              3737
5   Not rated    0.870112           0.0         1869              2148

================================================================================
cost_and_votes_outliers_by_price_range
Question: Are there outlier restaurants with extremely high Average Cost for two or Votes that significantly skew the averages for their respective price ranges?
================================================================================

,Price range,mean_cost,median_cost,max_cost,mean_votes,median_votes,max_votes
0,1,275.182943,300.0,450,44.597435,8.0,3591
1,2,596.826213,600.0,70000,147.607131,51.0,9667
2,3,5177.268466,1100.0,800000,443.860795,199.5,7931
3,4,1848.523891,2000.0,8000,368.595563,171.5,10934

================================================================================
rating_color_by_price_range
Question: How do the different Rating color categories correspond to the Price range of restaurants?
================================================================================

   Rating color  Price range  restaurant_count
0    Dark Green            1                32
1    Dark Green            2                69
2    Dark Green            3               126
3    Dark Green            4                74
4         Green            1               144
5         Green            2               325
6         Green            3               416
7         Green            4               194
8        Orange            1              1898
9        Orange            2              1425
10       Orange            3               313
11       Orange            4               101
12          Red            1                62
13          Red            2                98
14          Red            3                20
15          Red            4                 6
16        White            1              1700
17        White            2               402
18        White            3                35
19        White            4                11
20       Yellow            1               608
21       Yellow            2               794
22       Yellow            3               498
23       Yellow            4               200

================================================================================
online_delivery_by_currency
Question: What is the ratio of restaurants offering online delivery in countries where Indian Rupee is the currency versus other currencies?
================================================================================

,Currency,total_restaurants,delivery_restaurants,online_delivery_ratio,delivery_percentage
0,Indian Rupees(Rs.),8652,2423,0.280051,28.005086
1,Dollar($),482,0,0.000000,0.000000
2,Pounds(��),80,0,0.000000,0.000000
3,Brazilian Real(R$),60,0,0.000000,0.000000
4,Rand(R),60,0,0.000000,0.000000
5,Emirati Diram(AED),60,28,0.466667,46.666667
6,NewZealand($),40,0,0.000000,0.000000
7,Turkish Lira(TL),34,0,0.000000,0.000000
8,Botswana Pula(P),22,0,0.000000,0.000000
9,Indonesian Rupiah(IDR),21,0,0.000000,0.000000
10,Qatari Rial(QR),20,0,0.000000,0.000000
11,Sri Lankan Rupee(LKR),20,0,0.000000,0.000000

================================================================================
zero_coordinates_by_city
Question: Are there any specific cities where Longitude or Latitude values are frequently zero, potentially indicating missing or default geographic data?
================================================================================

            City  total_restaurants  zero_coord_count  zero_coord_pct
0      New Delhi               5473               233        4.257263
1          Noida               1080                94        8.703704
2        Gurgaon               1118                48        4.293381
3      Faridabad                251                22        8.764940
4       Vadodara                 20                10       50.000000
5      Mangalore                 20                 9       45.000000
6       Dehradun                 20                 7       35.000000
7       Varanasi                 20                 7       35.000000
8         Bhopal                 20                 6       30.000000
9         Nashik                 20                 6       30.000000
10      Guwahati                 21                 6       28.571429
11          Agra                 20                 6       30.000000
12     Allahabad                 20                 5       25.000000
13         Vizag                 20                 5       25.000000
14        Ranchi                 20                 4       20.000000
15       Lucknow                 21                 4       19.047619
16      Amritsar                 21                 4       19.047619
17    Aurangabad                 20                 4       20.000000
18  Bhubaneshwar                 21                 4       19.047619
19           Goa                 20                 3       15.000000
20         Patna                 20                 3       15.000000
21        Kanpur                 20                 2       10.000000
22      Ludhiana                 20                 2       10.000000
23      Auckland                 20                 1        5.000000
24       Colombo                 20                 1        5.000000
25        Nagpur                 20                 1        5.000000
26       Jakarta                 16                 1        6.250000
27        Mysore                 20                 1        5.000000